### ISSUE TITLE
Rename this repo to "capacitor-revenue-cat" or something indicating the affiliation

### ISSUE THREAD

**Issue by Gorgoroth** [Cap-go/capacitor-purchases#50]
To me, it's overbearing and misleading to call this plugin "capacitor-purchases" when it's *only* usable with a 3rd party service that costs money. It's fine that you offer it but be clear about it.

Your strategy seems to be to lure people in by making it seem like a universal plugin, when it is definitely not. Non-developer stakeholders suggest this as "of course there is a capacitor plugin for in app purchases" when it's really not. It's not even clear wether the service hosted in the USA is GDPR compliant, so not an option for a lot of projects.

**Comment by riderx** [comment]
Hello @Gorgoroth thanks for the feedback, the plugin will be soon migrated to Revenue-cat org, I hope that will resolve your issue, where I'm not affiliated with by the way.

I made it with revenue-cat because you cannot manage subscriptions without it, you need to develop 2 backend endpoint to meet security requirements, this is the only simple solution, and they do it for cheap.

For the data, they are US so probably not taking care of GDPR, the good part is the data they store is not personal if you don't send it intentionally, for example, they don't have email, they only store a unique per install device ID.

Please don't assume any intention more than just "having a simple solution for in-app subscription", I created it because my app https://captime.app was needing a simple solution.

**Comment by Gorgoroth** [comment]
Hey, thanks for taking the time to respond so thoughtfully. Sorry if I came across too accusing of motives. It's great that you made your work available to the community, that is appreciated very much!

Good intentions aside, I think it's still not a good choice to occupy the neutral namespace implying a wrapper for native functions on Github and especially NPM with a plugin that is very tightly coupled to a 3rd party service. The issues are many: compliance, cost, SLAs/availability/load and even uncertainty wether that service exists next year.

Anyway, glad you are taking action, take care! 🤗

**Comment by riderx** [comment]
No worries, I understood your point as well. That legit.
If I find a way in the near future to make a neutral version without 3rd party service.
I will do it, this one is going to RevenueCat, soon, so they will probably rename it to their org, so this name would be available.
