### ISSUE TITLE
question: Does this plugin have integration with the web?

### ISSUE THREAD

**Issue by rodrigoGA** [Cap-go/capacitor-purchases#62]
I have never used Revenuecat but from what I have seen it offers integration with stripe for the web.
I am looking for a solution that covers all platforms, web, ios and android.
Could I make subscriptions on the web with this plugin?
Thank you, and sorry for asking in this section

**Comment by riderx** [comment]
That a good question, for now it's not working in web, that could in the future !

**Comment by rodrigoGA** [comment]
Could you leave the request open or create a new one?  
so I can receive notification about this feature

**Comment by dliver-more** [comment]
+1 On web integration, at least for some parts. I think API endpoints that only GET information could be a helpful first pass, since many don't really relate to the device type. 

As a use case, I am creating a webapp version from a mobile app. I would like to be able to fetch user subscription status via the getCustomer endpoint. While the subscription may have been created in a specific platform, the status is stored in RC and is the same across all platforms. If device type is required by the RC SDK, you could even just pass a dummy value to allow a response.

**Comment by riderx** [comment]
For the web integration it's pretty easy to do it, if you want to work on it, i'm currently don't have the need right now, and the plugin will be transfer soon to official RC github

**Comment by dliver-more** [comment]
Thanks. I'm going to remove my above comment as I think it could expose the api keys and rather handle this through the backend. Thanks for the work!
